### ISSUE TITLE
404 on CSS file

### ISSUE THREAD

**Issue by SquareApple** [manovotny/wp-gist#36]
Should the folder in the package not be called wp-gist and not wp-gist-master? I get a 404 error trying to find wp-gist/css/style.min.css. Changed the plugins folder name and re-activated and all working.  Great Plugin :+1:  ta

**Comment by manovotny** [comment]
@SquareApple : : 

Yep, you're right.

I am [incorrectly expecting the plugin directory to be named `wp-gist`](https://github.com/manovotny/wp-gist/blob/master/classes/class-wp-gist.php#L123).

Great catch!
