### ISSUE TITLE
New theme (Nada) is changing Gist font

### ISSUE THREAD

**Issue by danwagnerco** [manovotny/wp-gist#38]
Hey @manovotny -- still getting great use out of your plugin, it's been working like gangbusters since your last recommendation.

This weekend, though, after changing themes (to [Nada by Paul Jarvis](https://nadatheme.com/)) it seems that the Gist font is now being influenced by the new theme:

![image](https://cloud.githubusercontent.com/assets/6598675/12538782/3934b56c-c2a8-11e5-85fc-650280e05524.png)

Here's a link to the post (and the Gist as well):

http://danwagner.co/how-to-delete-rows-with-a-for-loop/
https://gist.github.com/danwagnerco/7105f1123dd164f43c7f

How can I make sure the Gist fixed-width font remains?

**Comment by manovotny** [comment]
@danwagnerco : : 

Unless you already fixed something, things look good to me.

As you can see in the screenshot below, both your site and my site are using the `Consolas, "Liberation Mono", Menlo, Courier, monospace` font families, which come from the `embed-2106036b33ac9b6b00bf870ff8ac923e7be0ff3a95f80b24237005b45476ad10.css` file from GitHub.

![how_to_delete_rows_with_a_for_loop___dan_wagner_co_and_how_to_setup_phpstorm__xdebug__and_mamp_for_debugging](https://cloud.githubusercontent.com/assets/446260/12837250/3dad898e-cb86-11e5-9235-79c13578f824.jpg)

Based on what I am seeing, things look good to me!

Please let know if things look differently than that for you.

**Comment by danwagnerco** [comment]
Heya @manovotny -- really appreciate you following up!

I actually wound up doing an hour with a CSS expert on Air Pair to get it sorted out... money well spent. Once he explained to me what was happening, we solved the problem by:

1. Creating a child theme
2. Importing the Nada theme styles with `functions.php` in the child theme
3. Adding the following line to the child theme's `style.css`:

`.gist * { font-family: Consolas,"Liberation Mono",Menlo,Courier,monospace; }`

Boom! Styling corrected.

Thanks for the response again and have a great weekend,
Dan

**Comment by manovotny** [comment]
@danwagnerco : : 

Thanks for the follow up and glad you got things working!

Just so others don't hit this same problem, I added the same styles to the plugin and cut a new release.

Again, thanks for the feedback / follow up!
