### ISSUE TITLE
Cannot install on WP 4.4.2

### ISSUE THREAD

**Issue by gabelloyd** [manovotny/wp-gist#41]
I get a fatal error when uploading the plugin and activating it:

![screenshot 2016-04-08 18 31 19](https://cloud.githubusercontent.com/assets/2031438/14399192/41b1b276-fdb8-11e5-826d-ea440f83cc45.jpg)

**Comment by manovotny** [comment]
Sorry you're having issues.

Can you describe how you downloaded WP Gist?

**Comment by gabelloyd** [comment]
Hi @manovotny ,

I downloaded it from here: http://manovotny.github.io/wp-gist/

Thanks, Gabe

**Comment by manovotny** [comment]
My apologies... I changed the release process with the last release, so the download link was incorrect, so thank you for pointing it out.

I've got that all fixed up now, so give it a whirl again and let me know if you have any issues.

Thanks again!
